version: "3"
services:
  backend:
    image: hnc_backend:latest
    ports: 
      - 8000:8000
  # still need frontend image
  frontend:
    image: hnc_frontend:latest
    links:
      - backend
    environment:
      # add ENVs here
    ports:
      - 80:80