version: "3"
services:
  api:
    image: main_api:latest
    ports: 
      - 8000:8000
  billing:
    image: billing_api:latest
    ports:
      - 8001:8001
  temp:
    image: temp_api:latest
    ports:
      - 8002:8002
  frontend:
    image: hnc_frontend:latest
    links:
      - api
      - billing
      - temp
    environment:
      # add ENVs here
    ports:
      - 80:80