# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
        if [ -f billing-api/requirements.txt ]; then pip install -r billing-api/requirements.txt; fi
        if [ -f temp-api/requirements.txt ]; then pip install -r temp-api/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test api
      run: |
        cd api/src/
        pytest
    - name: Test billing
      run: |
        cd billing-api/src/
        pytest
    - name: Test temp
      run: |
        cd temp-api/src/
        pytest
