name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub Container Registry
      uses: docker/login-action@v2
      with:
        username: "hotncold"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Docker Main API image
      run: |
        git pull        
        cd api
        docker build . --file Dockerfile --tag hotncold/main_api:latest
    - name: Build Docker Billing API image
      run: |
        cd billing-api
        docker build . --file Dockerfile --tag hotncold/billing_api:latest
    - name: Build Docker Temp API image
      run: |
        cd temp-api
        docker build . --file Dockerfile --tag hotncold/temp_api:latest
    - name: Build Docker Frontend image
      run: |
        cd frontend/
        echo "REACT_APP_API_URL = 'http://46.101.92.174/api'" > .env
        yarn install && yarn build
        docker build . --file Dockerfile -t hotncold/frontend:latest
    - name: Push images to registry
      run: |
        docker push hotncold/main_api:latest
        docker push hotncold/billing_api:latest
        docker push hotncold/temp_api:latest      
        docker push hotncold/frontend:latest

