name: Docker Image CI

on:
  repository_dispatch:
    types: [trigger-workflow-3]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}
    - name: Deploy docker-compose
      run: docker-compose up
