name: Docker Image CI

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Deploy docker-compose
      run: docker-compose up
